# See https://github.com/google/mono_repo.dart for details
sdk:
- dev

stages:
- smoke_test:
  - group:
    - format
    - analyze: --fatal-infos .
    sdk:
    - beta
    - dev
    - edge
    - stable
    - 2.10.4
    - 2.12.0-259.0.dev
    - 2.12.0-29.10.beta
- test:
  - test: --test-randomize-ordering-seed=random
    os:
    - linux
