# See https://github.com/google/mono_repo.dart for details
dart:
- dev

stages:
- smoke_test:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-infos --fatal-warnings .
- unit_test:
  - test: --test-randomize-ordering-seed=random
    os:
      - linux
