# See https://github.com/google/mono_repo.dart for details
dart:
- dev

stages:
- smoke_test:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-infos .
    dart: [beta, dev, stable, 2.12.0-0.0.dev, 2.12.0-29.10.beta]
- unit_test:
  - test: --test-randomize-ordering-seed=random
    os:
      - linux
