# See https://github.com/google/mono_repo.dart for details
sdk:
- dev

stages:
- smoke_test:
  - group:
    - format
    - analyze: --fatal-infos .
    sdk:
    - beta
    - dev
    - edge
    - stable
    - pubspec
    - 2.17.0-69.1.beta
    - 2.18.0-106.0.dev
- test:
  - test_with_coverage: --test-randomize-ordering-seed=random
    os:
    - linux
