# See https://github.com/google/mono_repo.dart for details

stages:
- smoke_test:
  # https://github.com/google/mono_repo.dart/issues/199
  - command: cd ../ && dart mono_repo/bin/mono_repo.dart generate --validate
    sdk: dev
  - group:
    - format
    - analyze
    sdk: dev
  - analyze:
    sdk: pubspec
- test:
  - test: -P presubmit --test-randomize-ordering-seed=random
    os:
    - linux
    - windows
    sdk: pubspec
  - test_with_coverage: -P presubmit --test-randomize-ordering-seed=random
    sdk: dev
  - test: -P presubmit --test-randomize-ordering-seed=random
    os: windows
    sdk: dev
  - test_with_coverage: --test-randomize-ordering-seed=random
    sdk: dev
  - test: --test-randomize-ordering-seed=random
    sdk: dev

cache:
  directories:
  - .dart_tool/build
