# See https://github.com/google/mono_repo.dart for details

stages:
- smoke_test:
  # https://github.com/google/mono_repo.dart/issues/199
  - command: cd ../ && dart mono_repo/bin/mono_repo.dart generate --validate
    sdk: dev
  - group:
    - format
    - analyze: --fatal-infos .
    sdk: dev
  - analyze:
    sdk: 2.17.5
- test:
  - test: -x yaml -P presubmit --test-randomize-ordering-seed=random
    os:
    - linux
    - windows
    sdk: [2.17.5]
  - test_with_coverage: -x yaml -P presubmit --test-randomize-ordering-seed=random
    os:
    - linux
    sdk: [dev]
  - test: -x yaml -P presubmit --test-randomize-ordering-seed=random
    os:
    - windows
    sdk: [dev]
  - test_with_coverage: -t yaml --test-randomize-ordering-seed=random
    os:
    - linux
    sdk: [dev]
  - test: -t yaml --test-randomize-ordering-seed=random
    os:
    - linux
    sdk: [dev]

cache:
  directories:
  - .dart_tool/build
