# See https://github.com/google/mono_repo.dart for details
sdk:
- beta

stages:
- smoke_test:
  - group:
    - format
    - analyze: --fatal-infos .
    sdk:
    - beta
    - stable
    - master
- unit_test:
  - test: --test-randomize-ordering-seed=random
    os:
    - linux
