# Created with package:mono_repo v6.7.2
name: "Dart CI"
on:
  push:
    branches:
      - "main"
      - "master"
  pull_request: null
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: "bash"
env:
  PUB_ENVIRONMENT: "bot.github"
permissions:
  contents: "read"


jobs:
  job_001:
    name: "smoke_test; linux; `dart analyze --fatal-infos .`"
    runs-on: "ubuntu-latest"
    steps:
      - id: "checkout"
        name: "Checkout repository"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"
        with:
          persist-credentials: false
      - name: "Setup dart package"
        uses: "./.github/actions/setup-dart"
        with:
          sdk: "${{ matrix.sdk }}"
          working-directory: "test_pkg"
      - run: "dart analyze --fatal-infos ."
        working-directory: "test_pkg"
    strategy:
      fail-fast: false
      matrix:
        sdk:
          - "2.16.0"
          - "2.17.0-69.1.beta"
          - "2.18.0-106.0.dev"
          - "beta"
          - "dev"
          - "stable"
  job_002:
    name: "smoke_test; linux; Dart 3.8.0; `dart analyze --fatal-infos`"
    runs-on: "ubuntu-latest"
    steps:
      - id: "checkout"
        name: "Checkout repository"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"
        with:
          persist-credentials: false
      - name: "Setup dart package"
        uses: "./.github/actions/setup-dart"
        with:
          sdk: "3.8.0"
          working-directory: "mono_repo"
      - run: "dart analyze --fatal-infos"
        working-directory: "mono_repo"
  job_003:
    name: "smoke_test; linux; `flutter analyze --fatal-infos .`"
    runs-on: "ubuntu-latest"
    steps:
      - id: "checkout"
        name: "Checkout repository"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"
        with:
          persist-credentials: false
      - name: "Setup flutter package"
        uses: "./.github/actions/setup-flutter"
        with:
          channel: "${{ matrix.sdk }}"
          working-directory: "test_flutter_pkg"
      - run: "flutter analyze --fatal-infos ."
        working-directory: "test_flutter_pkg"
    strategy:
      fail-fast: false
      matrix:
        sdk:
          - "beta"
          - "stable"
  job_004:
    name: "smoke_test; linux; Dart dev; `cd ../ && dart mono_repo/bin/mono_repo.dart generate --validate`"
    runs-on: "ubuntu-latest"
    steps:
      - id: "checkout"
        name: "Checkout repository"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"
        with:
          persist-credentials: false
      - name: "Setup dart package"
        uses: "./.github/actions/setup-dart"
        with:
          sdk: "dev"
          working-directory: "mono_repo"
      - run: "cd ../ && dart mono_repo/bin/mono_repo.dart generate --validate"
        working-directory: "mono_repo"
  job_005:
    name: "smoke_test; linux; Dart dev; `dart format --output=none --set-exit-if-changed .`, `dart analyze --fatal-infos`"
    runs-on: "ubuntu-latest"
    steps:
      - id: "checkout"
        name: "Checkout repository"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"
        with:
          persist-credentials: false
      - name: "Setup dart package"
        uses: "./.github/actions/setup-dart"
        with:
          sdk: "dev"
          working-directory: "mono_repo"
      - run: "dart format --output=none --set-exit-if-changed ."
        working-directory: "mono_repo"
      - run: "dart analyze --fatal-infos"
        working-directory: "mono_repo"
  job_006:
    name: "smoke_test; linux; Dart main; `dart format --output=none --set-exit-if-changed .`, `dart analyze --fatal-infos --fatal-infos .`"
    runs-on: "ubuntu-latest"
    steps:
      - id: "checkout"
        name: "Checkout repository"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"
        with:
          persist-credentials: false
      - name: "Setup dart package"
        uses: "./.github/actions/setup-dart"
        with:
          sdk: "main"
          working-directory: "test_pkg"
      - run: "dart format --output=none --set-exit-if-changed ."
        working-directory: "test_pkg"
      - run: "dart analyze --fatal-infos --fatal-infos ."
        working-directory: "test_pkg"
  job_007:
    name: "smoke_test; linux; Flutter master; `dart format --output=none --set-exit-if-changed .`, `flutter analyze --fatal-infos --fatal-infos .`"
    runs-on: "ubuntu-latest"
    steps:
      - id: "checkout"
        name: "Checkout repository"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"
        with:
          persist-credentials: false
      - name: "Setup flutter package"
        uses: "./.github/actions/setup-flutter"
        with:
          channel: "master"
          working-directory: "test_flutter_pkg"
      - run: "dart format --output=none --set-exit-if-changed ."
        working-directory: "test_flutter_pkg"
      - run: "flutter analyze --fatal-infos --fatal-infos ."
        working-directory: "test_flutter_pkg"
  job_008:
    name: "test; linux; Dart 3.8.0; `dart test -P presubmit --test-randomize-ordering-seed=random`"
    runs-on: "ubuntu-latest"
    steps:
      - id: "checkout"
        name: "Checkout repository"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"
        with:
          persist-credentials: false
      - name: "Setup dart package"
        uses: "./.github/actions/setup-dart"
        with:
          sdk: "3.8.0"
          working-directory: "mono_repo"
      - run: "dart test -P presubmit --test-randomize-ordering-seed=random"
        working-directory: "mono_repo"
    needs:
      - "job_001"
      - "job_002"
      - "job_003"
      - "job_004"
      - "job_005"
      - "job_006"
      - "job_007"
  job_009:
    name: "test; linux; Flutter beta; `flutter test --test-randomize-ordering-seed=random`"
    runs-on: "ubuntu-latest"
    steps:
      - id: "checkout"
        name: "Checkout repository"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"
        with:
          persist-credentials: false
      - name: "Setup flutter package"
        uses: "./.github/actions/setup-flutter"
        with:
          channel: "beta"
          working-directory: "test_flutter_pkg"
      - run: "flutter test --test-randomize-ordering-seed=random"
        working-directory: "test_flutter_pkg"
    needs:
      - "job_001"
      - "job_002"
      - "job_003"
      - "job_004"
      - "job_005"
      - "job_006"
      - "job_007"
  job_010:
    name: "test; linux; Dart dev; `dart pub global run coverage:test_with_coverage -- --test-randomize-ordering-seed=random`"
    runs-on: "ubuntu-latest"
    steps:
      - id: "checkout"
        name: "Checkout repository"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"
        with:
          persist-credentials: false
      - name: "Setup dart package"
        uses: "./.github/actions/setup-dart"
        with:
          sdk: "dev"
          working-directory: "mono_repo"
      - name: "Activate package:coverage"
        run: "dart pub global activate coverage '>=1.5.0'"
      - run: "dart pub global run coverage:test_with_coverage -- --test-randomize-ordering-seed=random"
        working-directory: "mono_repo"
      - name: "Upload coverage to Coveralls"
        uses: "coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          path-to-lcov: "mono_repo/coverage/lcov.info"
          flag-name: "coverage_00"
          parallel: true
      - name: "Upload coverage to codecov.io"
        uses: "codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f"
        with:
          files: "mono_repo/coverage/lcov.info"
          fail_ci_if_error: false
          name: "coverage_00"
          token: "${{ secrets.CODECOV_TOKEN }}"
    needs:
      - "job_001"
      - "job_002"
      - "job_003"
      - "job_004"
      - "job_005"
      - "job_006"
      - "job_007"
  job_011:
    name: "test; linux; Dart dev; `dart pub global run coverage:test_with_coverage -- -P presubmit --test-randomize-ordering-seed=random`"
    runs-on: "ubuntu-latest"
    steps:
      - id: "checkout"
        name: "Checkout repository"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"
        with:
          persist-credentials: false
      - name: "Setup dart package"
        uses: "./.github/actions/setup-dart"
        with:
          sdk: "dev"
          working-directory: "mono_repo"
      - name: "Activate package:coverage"
        run: "dart pub global activate coverage '>=1.5.0'"
      - run: "dart pub global run coverage:test_with_coverage -- -P presubmit --test-randomize-ordering-seed=random"
        working-directory: "mono_repo"
      - name: "Upload coverage to Coveralls"
        uses: "coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          path-to-lcov: "mono_repo/coverage/lcov.info"
          flag-name: "coverage_01"
          parallel: true
      - name: "Upload coverage to codecov.io"
        uses: "codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f"
        with:
          files: "mono_repo/coverage/lcov.info"
          fail_ci_if_error: false
          name: "coverage_01"
          token: "${{ secrets.CODECOV_TOKEN }}"
    needs:
      - "job_001"
      - "job_002"
      - "job_003"
      - "job_004"
      - "job_005"
      - "job_006"
      - "job_007"
  job_012:
    name: "test; linux; Dart dev; `dart test --test-randomize-ordering-seed=random`"
    runs-on: "ubuntu-latest"
    steps:
      - id: "checkout"
        name: "Checkout repository"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"
        with:
          persist-credentials: false
      - name: "Setup dart package"
        uses: "./.github/actions/setup-dart"
        with:
          sdk: "dev"
          working-directory: "mono_repo"
      - run: "dart test --test-randomize-ordering-seed=random"
        working-directory: "mono_repo"
    needs:
      - "job_001"
      - "job_002"
      - "job_003"
      - "job_004"
      - "job_005"
      - "job_006"
      - "job_007"
  job_013:
    name: "test; linux; Dart dev; `dart pub global run coverage:test_with_coverage -- --test-randomize-ordering-seed=random`"
    runs-on: "ubuntu-latest"
    steps:
      - id: "checkout"
        name: "Checkout repository"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"
        with:
          persist-credentials: false
      - name: "Setup dart package"
        uses: "./.github/actions/setup-dart"
        with:
          sdk: "dev"
          working-directory: "test_pkg"
      - name: "Activate package:coverage"
        run: "dart pub global activate coverage '>=1.5.0'"
      - run: "dart pub global run coverage:test_with_coverage -- --test-randomize-ordering-seed=random"
        working-directory: "test_pkg"
      - name: "Upload coverage to Coveralls"
        uses: "coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          path-to-lcov: "test_pkg/coverage/lcov.info"
          flag-name: "coverage_02"
          parallel: true
      - name: "Upload coverage to codecov.io"
        uses: "codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f"
        with:
          files: "test_pkg/coverage/lcov.info"
          fail_ci_if_error: false
          name: "coverage_02"
          token: "${{ secrets.CODECOV_TOKEN }}"
    needs:
      - "job_001"
      - "job_002"
      - "job_003"
      - "job_004"
      - "job_005"
      - "job_006"
      - "job_007"
  job_014:
    name: "test; linux; Flutter stable; `flutter test --test-randomize-ordering-seed=random`"
    runs-on: "ubuntu-latest"
    steps:
      - id: "checkout"
        name: "Checkout repository"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"
        with:
          persist-credentials: false
      - name: "Setup flutter package"
        uses: "./.github/actions/setup-flutter"
        with:
          channel: "stable"
          working-directory: "test_flutter_pkg/example"
      - run: "flutter test --test-randomize-ordering-seed=random"
        working-directory: "test_flutter_pkg/example"
    needs:
      - "job_001"
      - "job_002"
      - "job_003"
      - "job_004"
      - "job_005"
      - "job_006"
      - "job_007"
  job_015:
    name: "test; windows; `dart test -P presubmit --test-randomize-ordering-seed=random`"
    runs-on: "windows-latest"
    steps:
      - id: "checkout"
        name: "Checkout repository"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"
        with:
          persist-credentials: false
      - name: "Setup dart package"
        uses: "./.github/actions/setup-dart"
        with:
          sdk: "${{ matrix.sdk }}"
          working-directory: "mono_repo"
      - run: "dart test -P presubmit --test-randomize-ordering-seed=random"
        working-directory: "mono_repo"
    needs:
      - "job_001"
      - "job_002"
      - "job_003"
      - "job_004"
      - "job_005"
      - "job_006"
      - "job_007"
    strategy:
      fail-fast: false
      matrix:
        sdk:
          - "3.8.0"
          - "dev"
  job_016:
    name: "Notify failure"
    runs-on: "ubuntu-latest"
    if: "(github.event_name == 'push' || github.event_name == 'schedule') && failure()"
    steps:
      - run: |
          curl -H "Content-Type: application/json" -X POST -d \
            "{'text':'Build failed! ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}'}" \
            "${CHAT_WEBHOOK_URL}"
        env:
          CHAT_WEBHOOK_URL: "${{ secrets.CHAT_WEBHOOK_URL }}"
    needs:
      - "job_001"
      - "job_002"
      - "job_003"
      - "job_004"
      - "job_005"
      - "job_006"
      - "job_007"
      - "job_008"
      - "job_009"
      - "job_010"
      - "job_011"
      - "job_012"
      - "job_013"
      - "job_014"
      - "job_015"
  job_17:
    name: "Mark Coveralls job finished"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Mark Coveralls job finished"
        uses: "coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          parallel-finished: true
    needs:
      - "job_010"
      - "job_011"
      - "job_013"

