# Created with package:mono_repo v6.6.5-wip
name: "package:test_flutter_pkg"
on:
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/test_flutter_pkg.yml
      - "test_flutter_pkg/**"
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  job_001:
    name: "smoke_test; linux; Flutter beta; `dart format --output=none --set-exit-if-changed .`, `flutter analyze --fatal-infos`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:beta;packages:test_flutter_pkg;commands:format_0-analyze_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:beta;packages:test_flutter_pkg
            os:ubuntu-latest;pub-cache-hosted;sdk:beta
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2
        with:
          channel: beta
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - id: test_flutter_pkg_pub_upgrade
        name: test_flutter_pkg; flutter pub upgrade
        run: flutter pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: test_flutter_pkg
      - name: "test_flutter_pkg; dart format --output=none --set-exit-if-changed ."
        run: "dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.test_flutter_pkg_pub_upgrade.conclusion == 'success'"
        working-directory: test_flutter_pkg
      - name: "test_flutter_pkg; flutter analyze --fatal-infos"
        run: flutter analyze --fatal-infos
        if: "always() && steps.test_flutter_pkg_pub_upgrade.conclusion == 'success'"
        working-directory: test_flutter_pkg
  job_002:
    name: "smoke_test; linux; Flutter master; `true`, `flutter analyze`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:master;packages:test_flutter_pkg;commands:format_1-analyze_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:master;packages:test_flutter_pkg
            os:ubuntu-latest;pub-cache-hosted;sdk:master
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2
        with:
          channel: master
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - id: test_flutter_pkg_pub_upgrade
        name: test_flutter_pkg; flutter pub upgrade
        run: flutter pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: test_flutter_pkg
      - name: test_flutter_pkg; true
        run: "true"
        if: "always() && steps.test_flutter_pkg_pub_upgrade.conclusion == 'success'"
        working-directory: test_flutter_pkg
      - name: test_flutter_pkg; flutter analyze
        run: flutter analyze
        if: "always() && steps.test_flutter_pkg_pub_upgrade.conclusion == 'success'"
        working-directory: test_flutter_pkg
  job_003:
    name: "smoke_test; linux; Flutter stable; `true`, `flutter analyze`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:test_flutter_pkg;commands:format_1-analyze_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:test_flutter_pkg
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2
        with:
          channel: stable
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - id: test_flutter_pkg_pub_upgrade
        name: test_flutter_pkg; flutter pub upgrade
        run: flutter pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: test_flutter_pkg
      - name: test_flutter_pkg; true
        run: "true"
        if: "always() && steps.test_flutter_pkg_pub_upgrade.conclusion == 'success'"
        working-directory: test_flutter_pkg
      - name: test_flutter_pkg; flutter analyze
        run: flutter analyze
        if: "always() && steps.test_flutter_pkg_pub_upgrade.conclusion == 'success'"
        working-directory: test_flutter_pkg
  job_004:
    name: "test; linux; Flutter beta; `flutter test --test-randomize-ordering-seed=random`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:beta;packages:test_flutter_pkg;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:beta;packages:test_flutter_pkg
            os:ubuntu-latest;pub-cache-hosted;sdk:beta
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2
        with:
          channel: beta
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - id: test_flutter_pkg_pub_upgrade
        name: test_flutter_pkg; flutter pub upgrade
        run: flutter pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: test_flutter_pkg
      - name: "test_flutter_pkg; flutter test --test-randomize-ordering-seed=random"
        run: "flutter test --test-randomize-ordering-seed=random"
        if: "always() && steps.test_flutter_pkg_pub_upgrade.conclusion == 'success'"
        working-directory: test_flutter_pkg
    needs:
      - job_001
      - job_002
      - job_003
  job_005:
    name: Notify failure
    runs-on: ubuntu-latest
    if: "(github.event_name == 'push' || github.event_name == 'schedule') && failure()"
    steps:
      - run: |
          curl -H "Content-Type: application/json" -X POST -d \
            "{'text':'Build failed! ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}'}" \
            "${CHAT_WEBHOOK_URL}"
        env:
          CHAT_WEBHOOK_URL: "${{ secrets.CHAT_WEBHOOK_URL }}"
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
